Api/urls.py
from firstapp.views import load_more_posts,follow_controller,search_recommend_api,username_warning,phonenumber_warning,thulo_post_data,handle_vitri_follow,postComments,bahiri_like,get_profile_posts,predict_crop_disease,news_api_proxy,load_following_posts,handle_profile_follow

from django.urls import path

urlpatterns=[
    path('getposts/',load_more_posts),
    path('follow/',follow_controller),
    path('username_warning/',username_warning),
    path('search_people_suggestion/',search_recommend_api),
    path('phonenumber_warning/',phonenumber_warning),
    path('thulo_post_data/',thulo_post_data),
    path('handle_vitri_follow/',handle_vitri_follow),
    path('handle_profile_follow/',handle_profile_follow),
    path("postComments/",postComments),
    path("bahiri_like/",bahiri_like),
    path('get_profile_posts/',get_profile_posts),
    path('predict_diesease/',predict_crop_disease),
    path('news/', news_api_proxy, name='news_api_proxy'),
    path('following_posts/',load_following_posts),
]

firstapp/urls.py
from django.urls import path
from .  import views

urlpatterns=[
    path("",views.login_page,name="login"),# this will trigger domain/challenges/
    path("home/",views.home,name="homepage"),
    path("home/forum",views.forum,name="forumpage"),
    path("register/",views.register,name="register"),
    path("logout/",views.logout_page,name="logout"),
    path("home/forum/profile",views.my_profile,name="my_profile"),
    path("home/forum/search",views.search_people,name="search_people"),
    path("home/forum/<slug:slug>",views.individual_people,name="individual_people"),
    path("cropInfo/",views.cropInfo,name="cropInfo"),
    path("crop_detail/<str:name>",views.crop_detail,name="crop_detail"),
    path('predict/',views.predict_crop_portal, name='predict'),
    path('recommend/',views.recommend, name='recommend'),
    path("following_feed",views.following_feed,name="following_feed"),
    path("forum/fans",views.fans,name="fans")
]
#pg_ctl start -D "C:\Program Files\PostgreSQL\16\data"

majorproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("firstapp.urls")),
    path("api/",include("Api.urls")),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

firstapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    username=models.CharField(max_length=150,unique=True)
    phone_number=models.CharField(unique=True)
    occupation=models.CharField(max_length=150,blank=True)
    profile_picture=models.FileField(upload_to='profile_pics',blank=True)#upload_to='profile_pics',
    slug=models.SlugField(default="",null=False,unique=True,db_index=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.username)
        super().save(*args,**kwargs)

    

class Post(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    post_text=models.TextField()
    post_image=models.FileField(upload_to='post_picture',blank=True)
    uploaded_date=models.DateTimeField(auto_now_add=True)
    no_of_likes=models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}-{self.uploaded_date}"
    

class Comment(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    comment_text=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.created_at}"
    

class Follow(models.Model):
    follower=models.ForeignKey(UserProfile,related_name="follower",on_delete=models.CASCADE)
    following=models.ForeignKey(UserProfile,related_name='following',on_delete=models.CASCADE)
    followed_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.follower.username} follows {self.following.username}"
    

class Like(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE)
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE)

#models for the crop information section 
class CropInfo(models.Model):
    name = models.CharField(max_length=100, unique=True)
    varieties = models.TextField()
    climate_and_soil_requirements = models.TextField()
    planting_time = models.TextField()
    watering_needs = models.TextField()
    fertilization = models.TextField()
    pest_and_disease_management = models.TextField()
    harvesting_time = models.TextField()
    post_harvest_handling = models.TextField()
    market_information = models.TextField()
    government_schemes_and_subsidies = models.TextField()
    picture=models.FileField(upload_to='crop_pics',blank=True)
    def __str__(self):
        return self.name

firstapp/forms.py
from django import forms

class loginform(forms.Form):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(attrs={'placeholder': 'Enter your username'})
    )
    # phone_number=forms.CharField(max_length=10,widget=forms.TextInput(attrs={'placeholder': 'phone number'}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password'}))


class user_post(forms.Form):
    post_text=forms.CharField(label="say something....",widget=forms.Textarea,required=True)
    post_image=forms.FileField(required=False)

class RegistrationForm(forms.Form):
    first_name=forms.CharField(max_length=30,widget=forms.TextInput(attrs={'placeholder': 'Enter your first name'}))
    last_name=forms.CharField(
        max_length=30,
        widget=forms.TextInput(attrs={'placeholder':'Enter your last name'})
    )
    username=forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter your name'}))
    occupation=forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter your occupation'}))
    phone_number =forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Enter phone number'})
    )
    email= forms.EmailField(max_length=100,
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'}),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'})
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password'})
    )
    profile_image=forms.FileField(label='Upload Profile Picture', required=False)
    # years_of_farming_experience=forms.CharField(required=False)



class CropPredictionForm(forms.Form):
    crop = forms.CharField(max_length=100)
    image = forms.ImageField()

firstapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseNotFound,HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
#from django.urls import reverse
#from django.template.loader import render_to_string
#from django.contrib.auth.hashers import make_password, check_password
from .forms import loginform,user_post,RegistrationForm,CropPredictionForm
from .models import UserProfile,Post,Follow,Comment,Like,CropInfo
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import PostSerializer,UserProfileSerializer,CommentSerializer

from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tensorflow.keras.models import load_model
import os
from django.conf import settings

#concept:           1.Django comes with a built-in user model called User. This model includes fields like username, password, and email. It also comes with features like password hashing and authentication methods.
modelstraw=load_model("F:/vs code/farmer/latest_models/strawberry.h5")
modelcorn=load_model("F:/vs code/farmer/latest_models/corn_latest.h5")
modelgrape=load_model('F:/vs code/farmer/latest_models/grape _latest.h5')
modelapple=load_model('F:/vs code/farmer/latest_models/apple.h5')
modelpotato=load_model('F:/vs code/farmer/latest_models/potato.h5')


def register(request):
    if request.method=='POST':
        form=RegistrationForm(request.POST,request.FILES)
        if form.is_valid():
            email=form.cleaned_data['email']
            password=form.cleaned_data['password']
            username=form.cleaned_data['username']
            first_name=form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            phone_number=form.cleaned_data['phone_number']
            occupation=form.cleaned_data['occupation']
            uploaded_photo=request.FILES["profile_image"]
            
            # Save the file to the media directory using FileSystemStorage
            file_path = os.path.join(settings.MEDIA_ROOT, 'profile_pics', uploaded_photo.name)
            # Save the file to MEDIA_ROOT
            with open(file_path, 'wb') as destination:
                for chunk in uploaded_photo.chunks():
                    destination.write(chunk)
        

            try:
                user = User.objects.create_user(username=username,email=email,password= password,first_name=first_name,last_name=last_name)#At this point, user is a User object that has already been saved to the database.
                #if you want to change other fields.
                    #>>> user.last_name = "Lennon"
                    #>>> user.save()
            
                    ##########Also creating a User Profile  
                user_prof_obj=UserProfile(user=user,username=username,phone_number=phone_number,occupation=occupation,profile_picture=file_path )
                user_prof_obj.save()
                return redirect('login')#Redirect to the login page after sucessful registration
            except:
                return HttpResponse('An error occurred while creating the user profile')
    
    
    else:
        logout(request)
        form=RegistrationForm()
    

    return render(request,"firstapp/register_page.html",{'form':form})





def login_page(request):
    if request.method == 'POST':
        form = loginform(request.POST)
        if form.is_valid():
            print('valid form')
            username= form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(request, username=username,password=password)#If the credentials are valid, the function returns a user object representing the authenticated user. 
                                                                              #If the credentials are invalid, the function returns None.
            
           ## eg. this gives the username of the user:::print(user.get_username())
            
            if user is not None:
                login(request,user)#yesle k garxa vane:
#                            -->aauta session banaidinxa ani tesma session data haru store gardinxa.tyo session id chai cookie ko rup ma send gardinxa browser lai.
#                            -->aba tyo data haru request.session.get('_auth_user_id',default='default') yesto garera herna milxa.
                return redirect('homepage')
    else:
        form = loginform()
    return render(request, 'firstapp/login.html', {'form': form})





# def login(request):
#     if request.method=='POST':
#         form=loginform(request.POST)
#         if form.is_valid():
#             phno=form.cleaned_data['phone_number']
#             password=form.cleaned_data['password']

#             try:
#                 user=UserProfile.objects.get(phone_number=phno)
#                 if password==user.password:
#                      # Password is correct, perform login logic here (e.g., setting session variables)
#                     print("correct")
#                     request.session['logged_status']='1'
#                     request.session.set_expiry(0)
#                     return  HttpResponseRedirect('/home')
#                     #return  redirect('homepage')
#                 else:
#                     return render(request,'firstapp/login.html', {'form': form})

#             except:
#                 return render(request,'firstapp/login.html', {'form': form})
            
#     else:
#         form=loginform()
#         return render(request,'firstapp/login.html',{'form':form})





def logout_page(request):
    logout(request)
    return redirect('login')
#the things done by logout(request) are:
#     -->The user is marked as not authenticated. The request.user attribute will be set to an instance of AnonymousUser, indicating that no user is currently logged in.
#     -->The user's session data is cleared. Any data stored in the session for that particular user will be removed.
#     -->The session cookie, which is used to identify the user's session, is cleared. This cookie typically stores the session ID
#     -->If your application uses Django's CSRF protection, the CSRF token for the user is invalidated
#     -->Any other authentication-related cookies, if present, may also be cleared.




@login_required(login_url="/")#The @login_required decorator in Django is used to restrict access to a view so that only authenticated users can access it. If a user is not authenticated, the decorator will redirect them to the login page.
def home(request):
    return render(request, 'firstapp/home.html')




@login_required(login_url="/")
def forum(request):
    if request.method=='POST':
        form=user_post(request.POST,request.FILES)
        current_user=request.user#current_user ma chai user_object aayo
        post_garne_user=current_user.username
        print(post_garne_user)
        if form.is_valid():
            #save the form to database
            post_text=form.cleaned_data['post_text']
            post_image = form.cleaned_data['post_image']
            user_profile_instance=UserProfile.objects.get(username=post_garne_user)
            post=Post(post_image=post_image,post_text=post_text,user=user_profile_instance)
            post.save()
            return HttpResponseRedirect("/home/forum")
    elif request.method=='GET':
        form=user_post()
    ##########################################################################
    request.session["first"] = "3000"#note this is temporary. yeslai api call mai if halera assign garne
    request.session["second"] ="2000"
    request.session["third"] ="1500"

    ###########################################################################

    return render(request, 'firstapp/forum.html', {'form': form})

@login_required(login_url="/")
def cropInfo(request):
    return render(request,"firstapp/infoHome.html")

@login_required(login_url="/")
def my_profile(request):
    if request.method=="GET":
        current_user=request.user
        user_profile_instance=current_user.userprofile
        image_src=user_profile_instance.profile_picture
        print(image_src)
        print(user_profile_instance.username)#upto here it is correct aba profile picture pani capture garne form banayera profile picture store garnaparyo. ani tesko url chai tyo template ko src ma halera pathaidinu paryo.

        #for finding the total number of followers:
        follower_count=Follow.objects.filter(following=user_profile_instance).count()

        #for finding the number of following
        following_count=Follow.objects.filter(follower=user_profile_instance).count()

        message="EditProfile"
##########################################################################
        request.session["f"] = "3000"#note this is temporary. yeslai api call mai if halera assign garne
        request.session["s"] ="2000"
        request.session["t"] ="1500"

###########################################################################


        return render(request,"firstapp/profile.html",{"user_profile":user_profile_instance,"follower":follower_count,"following":following_count,"message":message})


@login_required(login_url="/")
def search_people(request):#search ma lekhera enter dabayesi
    if(request.method=="GET"):
        currentuser_profile_obj=UserProfile.objects.get(username=request.user.username)
        if "query" in request.GET:
            query=request.GET['query']
            try:
                user_profile_instance=UserProfile.objects.get(username__iexact=query)
                follower_count=Follow.objects.filter(following=user_profile_instance).count()

firstapp/templates/firstapp/cropDetail.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ crop.name }} Details</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .navbar {
            background-color: #333;
            overflow: hidden;
            display:flex;
            justify-content:space-between;
        }

        .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .navbar a:hover {
            background-color: silver;
            color: black;
        }

        .content {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            display:flex;
            flex-direction:column;
        }

        .image_container {
            text-align: center;
        }

        .img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }

        .informations {
            margin-top: 20px;
        }

        h1 {
            color: #333;
            text-transform: capitalize;
            border-top:1px solid grey;
        }

        ol {
            margin: 0;
            padding-left: 20px;
        }
        .heading{
            border-top:none;
            align-self:center;
        }
    </style>
</head>

<body>
    <div class="navbar">
        <a href="{%url "cropInfo"%}"><i class="fas fa-backward"></i> Back</a>
        <a href="{% url "homepage"%}">Home</a>
    </div>

    <section class="content">
        <h1 class="heading">{{crop.name}} Details</h1>
        <div class="image_container">
            <img src="{{crop.picture.url}}" alt="{{crop.name}}" class="img">
        </div>
        <div class="informations">
            <div class="varieties">
                <h1>varieties</h1>
                <ol class="var">
                    {{crop.varieties|safe}}
                </ol>
            </div>
            <div class="climateandsoil">
                <h1>climate and soil</h1>
                {{crop.climate_and_soil_requirements}}
            </div>
            <div class="planting_time">
                <h1>planting time</h1>
                {{crop.planting_time}}
            </div>
            <div class="watering_needs">
                <h1>watering needs</h1>
                {{crop.watering_needs}}
            </div>
            <div class="fertilization">
                <h1>fertilization</h1>
                {{crop.fertilization}}
            </div>
            <div class="pest_and_diesease">
                <h1>pest and disease</h1>
                {{crop.pest_and_disease_management}}
            </div>
            <div class="harvesting_time">
                <h1>harvesting time</h1>
                {{crop.harvesting_time }}
            </div>
            <div class="post_harvest_handling">
                <h1>post harvest handling</h1>
                {{crop.post_harvest_handling}}
            </div>
            <div class="Market_Information">
                <h1>market information</h1>
                {{crop.market_information}}
            </div>
            <div class="government_schemes">
                <h1>government schemes</h1>
                {{crop.government_schemes_and_subsidies}}
            </div>
        </div>
    </section>

    <script>
        // Add any JavaScript functionality here
    </script>
</body>

</html>

firstapp/templates/firstapp/profile_error.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Not found</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>{{error_message}}</h1>
    </body>
</html>

firstapp/templates/firstapp/register_page.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">

        <style>
            body {
                font-family: 'Arial', sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
            }
    
            form {
                max-width: 600px;
                height:auto;
                display:flex;
                flex-direction:column;
                margin: 20px auto;
                background-color: #fff;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }
    
            .c1 {
                display:flex;
                flex-direction:column;
                margin:17px 0;
            }
            p{
                margin:0;
            }
    

    
            input {
                width: 100%;
                padding: 10px;
                margin-top: 5px;
                box-sizing: border-box;
                border: 1px solid #ccc;
                border-radius: 4px;
            }


    
            button {
                background-color: #4caf50;
                color: #fff;
                padding: 10px 15px;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }
    
            button:hover {
                background-color: #45a049;
            }
            #f9{
                font-weight:bold;
            }
            #i{
                align-self:center;
            }
            #id_profile_image{
                border:none;
                
            }
            #p3,#p5{
                color:rgba(255,0,0,0.6);
                padding-left:10px;
            }
    </style>
    </head>
    <body>
        <form action="{%url 'register'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="c1" id="a">
                <p id="f1">{{form.first_name.label}}</p>
                {{form.first_name}}
                <p class="para" id="p1"><p>
            </div>
            <div class="c1" id="b">
                <p id="f2">{{form.last_name.label}}</p>
                {{form.last_name}}
                <p class="para" id="p2"><p>
            </div>
            <div class="c1" id="c">
                <p id="f3">{{form.username.label}}</p>
                {{form.username}}
                <p class="para" id="p3"><p>
            </div>
            <div class="c1" id="d">
                <p id="f4">{{form.email.label}}</p>
                {{form.email}}
                <p class="para" id="p4"><p>
            </div>
            <div class="c1" id="e">
                <p id="f5">{{form.phone_number.label}}</p>
                {{form.phone_number}}
                <p class="para" id="p5"><p>
            </div>
            <div class="c1" id="f">
                <p id="f6">{{form.occupation.label}}</p>
                {{form.occupation}}
                <p class="para" id="p6"><p>
            </div>
            <div class="c1" id="g">
                <p id="f7">{{form.password.label}}</p>
                {{form.password}}
                <p class="para" id="p7"><p>
            </div>
            <div class="c1" id="h">
                <p id="f8">{{form.confirm_password.label}}</p>
                {{form.confirm_password}}
                <p class="para" id="p8"><p>
            </div>
            <div class="c1" id="i">
                <p id="f9">{{form.profile_image.label}}</p>
                {{form.profile_image}}
            </div>
            <button id="button">submit</button>
        </form>

        
        <script>
            
//------------------------------------------------------------------------------------------------------------------------------------------------------------//            
                                //dynamically telling whether the username is taken or not
//-------------------------------------------------------------------------------------------------------------------------------------------------------------//
            username=document.querySelector("#id_username")
            username.addEventListener("input",async function(event){
                searchQuery=username.value;
                console.log(searchQuery);
                if (searchQuery!==" "){
                    try{
                        const response=await fetch(`http://127.0.0.1:8000/api/username_warning/?query=${encodeURIComponent(searchQuery)}`)
                        if(!response.ok){
                            throw new Error(`HTTP error ! status: ${response.status}`);
                        }
                        const data=await response.json()
                        updateSearchResultsUI(data);
                    }catch{
                        console.error("error:",error);
                    }
                }
                else{
                    //clear the search results if the search query is empty
                    clearSearchResults();
                  }
            });
            function clearSearchResults(){
                var under_paragraph=document.querySelector("#p3");
                var box=document.querySelector("#id_username");
                var button=document.querySelector("#button");
                box.style.backgroundColor="white";
                under_paragraph.innerText="";
                button.style.display="block";
            }
            function updateSearchResultsUI(data){
                clearSearchResults();
                var box=document.querySelector("#id_username")
                var under_paragraph=document.querySelector("#p3");
                var button=document.querySelector("#button");
                if (data.message=="yes"){
                    under_paragraph.innerText="username already taken";
                    box.style.backgroundColor="rgba(255,0,0,0.3)";
                    button.style.display="none";
                }
            }
//------------------------------------------------------------------------------------------------------------------------------------------------------------------//            
            phonenumber=document.querySelector("#id_phone_number")
            phonenumber.addEventListener("input",async function(event){
                searchQuery=phonenumber.value;
                console.log(searchQuery);
                if (searchQuery!==""){
                    try{
                        const response=await fetch(`http://127.0.0.1:8000/api/phonenumber_warning/?query=${encodeURIComponent(searchQuery)}`)
                        if(!response.ok){
                            throw new Error(`HTTP error ! status: ${response.status}`);
                        }
                        const data=await response.json()
                        updateSearchResultsUI2(data);
                    }catch{
                        console.error("error:",error);
                    }
                }
                else{
                    //clear the search results if the search query is empty
                    clearSearchResults2();
                  }
            });
            function clearSearchResults2(){
                var under_paragraph=document.querySelector("#p5");
                var box=document.querySelector("#id_phone_number");
                var button=document.querySelector("#button");
                box.style.backgroundColor="white";
                under_paragraph.innerText="";
                button.style.display="block";
            }
            function updateSearchResultsUI2(data){
                clearSearchResults2();
                var box=document.querySelector("#id_phone_number")
                var under_paragraph=document.querySelector("#p5");
                var button=document.querySelector("#button");
                if (data.message=="yes"){
                    under_paragraph.innerText="Phonenumber already taken";
                    box.style.backgroundColor="rgba(255,0,0,0.3)";
                    button.style.display="none";
                }
            }
        </script>
    </body>
</html>